### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 9mm** [cmdcolin/dotfiles#2]
Hey, I found this repo from here: https://www.reddit.com/r/neovim/comments/10kdg4y/autoformat_with_lspzero/

I am having a hellish time just trying to get formatting working. It doesnt seem "hard" per se but there is a large amount of reading required for LSP, and so far I have spent like 30 hours converting my vim config to neovim... at this point im just really tired. This is the only excrutiating area that is just dragging on forever.

I was wondering if you could explain some things about your config quickly...

1. how/why are you using null-ls? I thought that is an alternative to lsp-zero
2. is there a way to get formatters installed with mason, but configure them with `formatter.nvim`? is that crazy? Its super convenient to have Mason in charge of all of the installation, etc.

Well... I suppose that is my main question.

Right now I'm using lsp-zero with Mason. It seems the LSP's work fine (ruby, typescript, javascript, etc). I read in LSP docs that lsp-zero does not automatically set up formatters though, only LSPs.

My goal however is to use `eslint` and `typescript` for fixes, but nothing else. Currently when I run `vim.lsp.buf.format()` its also formatting HTML and doing all kinds of crazy stuff.

So far the things I'm trying to fix/do:

1. use eslint / typescript for formatting, only
2. load the formatters from Mason as opposed to manually installing everything... ideally
3. disable whatever this formatter garbage is thats happening when I run vim.lsp.buf.format() (maybe formatter.nvim fixes this)

```lua
return {
  'VonHeikemen/lsp-zero.nvim',
  enabled = true,
  branch = 'v2.x',
  dependencies = {
    { 'neovim/nvim-lspconfig' },
    {
      'williamboman/mason.nvim',
      build = function()
        pcall(function() vim.cmd('MasonUpdate') end)
      end,
    },
    { 'williamboman/mason-lspconfig.nvim' },
    { 'hrsh7th/nvim-cmp' },
    { 'hrsh7th/cmp-nvim-lsp' },
    { 'L3MON4D3/LuaSnip' },
  },
  config = function()
    local lsp = require('lsp-zero').preset({
      manage_nvim_cmp = {
        -- disable mappings so I can get <C-e> to work
        set_basic_mappings = false,
      },
    })

    lsp.on_attach(function(_, bufnr)
      lsp.default_keymaps({
        buffer = bufnr,
        preserve_mappings = true,
      })

      -- disable lsp semantic highlights
      -- client.server_capabilities.semanticTokensProvider = nil
    end)

    local config = require('lspconfig')

    config.lua_ls.setup(lsp.nvim_lua_ls())

    -- dap, linter, formatter are not auto-added by mason

    lsp.setup()

    vim.diagnostic.config({
      virtual_text = false,
      update_in_insert = false,
      underline = true,
    })

    -- this is awful
    -- vim.keymap.set('n', '<Leader>ee', vim.lsp.buf.format, { silent = true })

    -- cmp
    local cmp = require('cmp')
    local cmp_confirm = cmp.mapping.confirm({ select = false })

    cmp.setup({
      mapping = {
        ['<CR>'] = cmp_confirm,
        ['<C-e>'] = cmp_confirm,
        ['<C-d>'] = cmp.mapping.scroll_docs(4),
        ['<C-u>'] = cmp.mapping.scroll_docs(-4),
        ['<C-p>'] = cmp.mapping(function() if cmp.visible() then cmp.select_prev_item({ behavior = 'select' }) else cmp.complete() end end),
        ['<C-n>'] = cmp.mapping(function() if cmp.visible() then cmp.select_next_item({ behavior = 'select' }) else cmp.complete() end end),
      },
    })
  end,
}
```

**Comment by cmdcolin** [comment]
hey this is definitely an interesting issue. I will note, I basically just run prettier on save, via null-ls which integrates with prettier . I previously used formatter.nvim to run prettier on save but I switched to null-ls because it seemed like all the cool kids were doing it. But, now jull-ls may go unmaintained so back to searching. Formatter.nvim is not bad, it is just sort of a lot of configuration. I can check out your comments in more detail soon but I would be wary of eslint for formatting. For one, eslint can be slow, and for two, eslint is best at being a linter rather than a formatter. My setup gives me eslint warning inlays but doesn't autofiz eslint on save.

**Comment by cmdcolin** [comment]
I am also not aware of fixes that typescript does "automatically"? Are there any?

**Comment by 9mm** [comment]
@cmdcolin sorry you are correct on `typescript`, that was a typo.. or rather a brain typo, I don't even know why I included that in the list.

That's funny you mentioned null-ls, just after I spent an entire day reading about it I stumble upon the issue where it's going to be archived in 2 days 🤦🏻‍♂️

Right now, I suppose I'm going to just look at kickstart.nvim and try to do it that way, manually, with mason. And then on top of that I will try to add formatter and configure it.

Perhaps you can enlighten me on any misconceptions I have... but prettier when I tried it many years ago just got on my nerves with all of it's decisions. I'm sure it's very customizable (or is it very opinionated?), but the choices it made for formatting javascript were just egregious. It was so far off I didn't even bother trying to fix it. 

The reason I like `eslint` specifically is because I use the [AirBnB style guide](https://github.com/airbnb/javascript) for eslint, which is _nearly_ perfect to me, aside from maybe 3-4 changes. Having eslint fix according to this exact style guide is extremely preferable to me as each project can define the actual styles as a package. I don't know if prettier can do that, but I'm assuming no considering all the rules are eslint rules.

I will say though... I don't like how I also can't do fancy things like auto imports, etc... so not sure how to resolve that. Up until now I've just given up on that.

Regarding slowness I haven't noticed that as I used to use `vim-ale` to auto-check and fix on `<leader>e` which was very fast, or at least not noticeably slow. I really only wanted to fix the current buffer anyway, not just the entire project automatically.

I'm open to using prettier though I suppose, but it would be unfortunate to lose the airBNB config as that's an awful lot of reconfiguring. Maybe I can use prettier for other languages like ruby or something...

**Comment by cmdcolin** [comment]
hope you've been able to find a good config. i have just now made a lot of other random changes to my config. the only constant is change :) as of this comment, config is https://github.com/cmdcolin/dotfiles/blob/34415eda3a3a0a9c0ecbf24aef7f7504f2c1f232/init.lua

 random other comments in response to your older post


>I'm sure it's very customizable (or is it very opinionated?), but the choices it made for formatting javascript were just egregious. It was so far off I didn't even bother trying to fix it.

prettier is definitely a bit opinionated. there are a couple configs (number of spaces to use in an indent, whether to use semicolons or not) but not too many knobs. I've come to like it, and have gotten rid of most eslint stylings...except curly...I like that eslint adds curlies. wrote about that here :) https://cmdcolin.github.io/posts/2023-08-20-typescriptlint

>I will say though... I don't like how I also can't do fancy things like auto imports, etc... so not sure how to resolve that

i think, if i undersstand what you mean by auto-import, that a proper lsp setup with completions can do auto-imports. e.g. if you are typing MyCla then a popup completion menu will come up automatically (no button presses needed) and suggest MyClass, and then you select that from the popup, and it will complete that where you are typing and add the import statement at the top of the file to auto-import MyClass from whatever module it is from (npm module...local module, etc)

**Comment by 9mm** [comment]
Hey, I've actualy done a ton of work on my config since then, almost entirely revamped, but did end up removing prettier. i might try again though... i agree with you there i may be able to get used to it, i just hate the html formatting trying to split attributes

Thanks for your answer! You could close this if you want as i dont want to pollute your issues.

**Comment by cmdcolin** [comment]
good stuff:)
